version: "3"
services:
  redis:
    image: redis:7.0.12
    container_name: redis
    ports:
      - "6374:6379"
  proxypool:
    image: "germey/proxypool:master"
    container_name: proxypool
    ports:
      - "5555:5555"
    restart: always
    # volumes:
    #   - proxypool/crawlers/private:/app/proxypool/crawlers/private
    environment:
      PROXYPOOL_REDIS_HOST: redis
      
